import "./globals.css";
import type { Metadata } from "next";
import { Cormorant_Garamond, Lato } from "next/font/google";

// import { SessionInitializer } from "@/components/session_initializer";
import NavBar from "@/components/nav_bar";

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-cormorant",
});

const lato = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "700", "900"],
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "New Collection Linea",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable} ${cormorant.variable} antialiased bg-white max-w-[1500px] mx-auto`}
      >
        {/* <SessionInitializer /> */}
        <NavBar />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
